### ISSUE TITLE
error while compiling: Could NOT find Vulkan (missing: Vulkan_LIBRARY)

### ISSUE THREAD

**Issue by KestutisMa** [Glavnokoman/vuh#22]
I flowed compilation steps from https://github.com/Glavnokoman/vuh/blob/master/doc/build_install.md, tried `export Vulkan_LIBRARY=/home/a/Documents/vuh/include` (where is vulkan.h), but it doesn't help.
ubuntu 18.04

**Comment by Glavnokoman** [comment]
Sorry was on vacation.
What exactly is the error you are getting?

**Comment by KestutisMa** [comment]
Thanks for explanation. Now it is working. ;-)
