### ISSUE TITLE
bug in copy_async 

### ISSUE THREAD

**Issue by teub** [Glavnokoman/vuh#45]
I think there's a bug here, copy_async.hpp line 208:
`
			return Delayed<Copy>{
				         stage.copy_async(device_begin(stage.array), device_end(stage.array), dst_begin)
			          , Copy::wrap(std::move(stage))
			};
`
"std::move(stage)" can actually destroy/move "stage" before it is used in stage.copy_async

Here's a proposed fix:

`
			auto cpy = stage.copy_async(device_begin(stage.array), device_end(stage.array), dst_begin);
			return Delayed<Copy>{
				      std::move(cpy)
			          , Copy::wrap(std::move(stage))
			};
`

It seems to work now, but TBH I have no idea about how the whole thing works, I'm lost with all the std::move's

Edit: had the bug with VS, not sure about other compilers. Also had some weird compilation errors with templates, but I don't think they're related

**Comment by Glavnokoman** [comment]
Thanks! I think you are right, this looks like a bug.
In general 1.x branch is a dead end. I would suggest using the 2.x branch (unreleased yet, but functional). Copying stuff has been mostly rewritten there, so hopefully this particular UB is gone.
And please report the VS compilation errors.

**Comment by teub** [comment]
I don't know if that's a legit error or a VS bug, but here it is:

`include\vuh\delayed.hpp(102,1): error C2580: 'vuh::Delayed<vuh::detail::Noop>::Delayed(vuh::Delayed<vuh::detail::Noop> &&)': multiple versions of a defaulted special member functions are not allowed`

Seems to happen because of this line:
`Delayed(Delayed&& other) = default;`

I fixed it by commenting it out.

Also, a warning here:
`auto size_bytes() const-> uint32_t {return _size*sizeof(T);}`
` warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data`

**Comment by teub** [comment]
Btw I tried to switch to the vuh2 branch but it's not clear what changes I need to do to my code; are there any sample that I can use as a reference? It seems the examples are still using the master branch.

thanks!

**Comment by teub** [comment]
Btw2, when I switched back to the master branch (without my "fixes"), I no longer have a compilation error of any sort, nor any crash. I'm super confused but I thought I should let you know. (warnings are still there though).

It makes me suspect that the compilation error was a compiler bug, and the initial bug I reported is probably not a deterministic one.

thanks

**Comment by Glavnokoman** [comment]
Initial bug is a UB bit it is still a bug. I just released your suggested fix. Thanks.
The examples are not ported yet. That's actually one of the things lacking to get 2.0 released.
