### ISSUE TITLE
Linking problem on MacOS

### ISSUE THREAD

**Issue by Zhylkaaa** [Glavnokoman/vuh#47]
I am trying to use this tool and run code provided in Tutorial, but I keep getting this:

```Undefined symbols for architecture x86_64:
  "vuh::Device::createPipeline(vk::PipelineLayout, vk::PipelineCache, vk::PipelineShaderStageCreateInfo const&, vk::Flags<vk::PipelineCreateFlagBits>)", referenced from:
      vuh::detail::SpecsBase<vuh::typelist<unsigned int> >::init_pipeline() in main.cpp.o
  "vuh::Device::selectMemory(vk::Buffer, vk::Flags<vk::MemoryPropertyFlagBits>) const", referenced from:
      vuh::arr::AllocDevice<vuh::arr::properties::Device>::findMemory(vuh::Device const&, vk::Buffer, vk::Flags<vk::MemoryPropertyFlagBits>) in main.cpp.o
      vuh::arr::AllocDevice<vuh::arr::properties::Host>::findMemory(vuh::Device const&, vk::Buffer, vk::Flags<vk::MemoryPropertyFlagBits>) in main.cpp.o
      vuh::arr::AllocDevice<vuh::arr::properties::HostCoherent>::findMemory(vuh::Device const&, vk::Buffer, vk::Flags<vk::MemoryPropertyFlagBits>) in main.cpp.o
      vuh::arr::AllocDevice<vuh::arr::properties::HostCached>::findMemory(vuh::Device const&, vk::Buffer, vk::Flags<vk::MemoryPropertyFlagBits>) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [vuh_example_saxpy] Error 1
make[2]: *** [CMakeFiles/vuh_example_saxpy.dir/all] Error 2
make[1]: *** [CMakeFiles/vuh_example_saxpy.dir/rule] Error 2
make: *** [vuh_example_saxpy] Error 2
```

My MacOS version is 10.15.2 (Catalina). 
I followed steps provided in build&install and it worked fine
I am using CLion and it can find vuh/vuh.h, also it compiles shader

Can somebody tell me what I am doing wrong?

**Comment by Glavnokoman** [comment]
looks like you are not linking the `libvuh.so` or whatever is its equivalent on MacOS.

**Comment by Zhylkaaa** [comment]
Hear is my CMakeLists.txt

```
cmake_minimum_required(VERSION 3.8)
project(vuh_example_saxpy)

set(CMAKE_CXX_STANDARD 14)

find_package(Vuh REQUIRED)
find_package(Catch2 REQUIRED)

vuh_compile_shader(example_shader_saxpy
        SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/saxpy.comp
        TARGET ${CMAKE_CURRENT_BINARY_DIR}/saxpy.spv
        )

add_executable(vuh_example_saxpy main.cpp)

target_link_libraries(vuh_example_saxpy PUBLIC vuh::vuh)
target_link_libraries(vuh_example_saxpy PUBLIC Catch2::Catch2)
link_directories(/usr/local/lib)

add_dependencies(vuh_example_saxpy example_shader_saxpy)
```

it appears that Cmake no longer link /usr/local/lib automatically, but adding `link_directories` doesn't help much. It seems to me that `libvuh.so` equivalent for MacOS is `libvuh.dylib`

I actually can use `cmake .` in vuh directory directory and then use `make` in `doc/examples/saxpy`, but in separate project it doesn't work, so I guess I miss some linking commands or includes in `CMakeLists.txt`.

**Comment by Glavnokoman** [comment]
So, you are using CMake... good. Your CMakeLists.txt looks OK (apart from link_directories). Now if  cmake config step runs without errors I do not see how you can end up with missing lib. Maybe your installation did not go well, cause doc/examples/saxpy can pick up the library compiled in the same tree. You may want to run with VERBOSE flag to see what is the actual build command. Anyway it looks like you messed with one or more from cmake-config/vuh-install/cmake-build steps in the order of likelihood.
