### ISSUE TITLE
Error in the function read_spirv

### ISSUE THREAD

**Issue by lmreia** [Glavnokoman/vuh#56]
The latest release (version 1.1.3) works with no problems, but the most recent version of the master branch does not (tested after commit 4d241ed4d8419f1f67218667688a7337e56b76a4).

When I tried to run the example vuh_example_saxpy, I got the following error:

```
terminate called after throwing an instance of 'vk::InitializationFailedError'
  what():  vk::Device::createShaderModule: ErrorInitializationFailed
```

I noticed that the function `read_spirv` is not returning the proper data.
After I modified the function to be the same as it was in the release 1.1.3, the program worked.

Tested with visual c++ and mingw (msys2) on Windows 10.

**Comment by Glavnokoman** [comment]
Thanks for reporting this. I can confirm I see the same issue on Linux. And the unit tests are broken in `master`.

**Comment by Glavnokoman** [comment]
should be fixed now. please confirm it works for you.

**Comment by lmreia** [comment]
It seems to be working now. I'm closing the issue.
