### ISSUE TITLE
Allow users to specify entry point of compute shader

### ISSUE THREAD

**Issue by reeselevine** [Glavnokoman/vuh#61]
I'm using clspv (https://github.com/google/clspv) to generate some SPIRV shaders, and it's nice to be able to specify the entry point names myself.

I noticed you're not actively developing this project too much anymore, so I'm happy to contribute to it myself. Also have a couple other improvements I might file as well if I keep working on vulkan compute shaders!

**Comment by Glavnokoman** [comment]
Take a look at vuh2 branch. I remember implementing it. That branch was ready for release just lacked some polishing and was never actually released.

Contributions are welcome. Especially to the 2.0 branch, cause 1.x was a dead end.

**Comment by Glavnokoman** [comment]
Implemented in the 2.0 branch.
