### ISSUE TITLE
Push constants vs Uniform buffers

### ISSUE THREAD

**Issue by mpottinger** [Glavnokoman/vuh#64]
Hello, first of all I would like to thank you for this amazing library. It is literally a life saver for me. I am a newbie to vulkan but I have done a lot of work with compute shaders in OpenGL ES on Android and the limitations were just getting in the way too much. I needed to convert over to Vulkan but it is very verbose. This library is exactly what I would need to implement myself for my project to work.

One thing I am curious about though is the question of updating push constants for every frame. I am sending some depth/image data to my shaders via buffers, and also sending a 4x4 matrix. Push constants seem to work just fine for this, but I am wondering about performance, even if it may be a micro optimization.

I am no Vulkan expert but what I have read indicates that sending push constants involves re-building the command buffer, while using a uniform buffer you only need update the memory and re-use the same command buffer. It is unclear which is the more efficient method when updating every frame. So far in all your examples it is showing push constants being updated for every run. 

It certainly isn't slow, but I am just curious if there is anything that can be optimized here if possible, or if this is already the ideal method of updating every frame.

Thanks again! This library is perfect, it is a shame it is not more popular and under heavy development. For me it is the perfect GPGPU implementation, I love it.

**Comment by Glavnokoman** [comment]
You are very welcome, I am glad you find it useful.

If you do care about performance I would suggest to not believe anyone's words and do a benchmark yourself. As I understand the push constants they were designed with precisely your use case in mind. But!!! The actual performance is determined by the particular hardware/drivers combination.
